<Project>
  <PropertyGroup>
    <ProductVersion>0.0.1</ProductVersion>
    <ProductAssemblyVersion>0.0.1.0</ProductAssemblyVersion>
    <ProductRuntimeIdentifier>win-x64</ProductRuntimeIdentifier>
    <Version>$(ProductVersion)</Version>
    <AssemblyVersion>$(ProductAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(ProductAssemblyVersion)</FileVersion>
    <InformationalVersion>$(ProductVersion)</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ProductRuntimeIdentifier</_Parameter1>
      <_Parameter2>$(ProductRuntimeIdentifier)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ProductVersion</_Parameter1>
      <_Parameter2>$(ProductVersion)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
