using System.Collections.Frozen;
using System.Xml.Linq;

namespace Neuterradise.App.Localization;

/// <summary>
/// The EN/ID surface string tables shipped as embedded XML (the former WPF resource dictionaries,
/// kept byte-for-byte as data). They take precedence over the code tables in <see cref="SurfaceText"/>,
/// exactly as the resource dictionaries did. Parsed once, lazily, off any hot path.
/// </summary>
internal static class LocalizationTables
{
    private static readonly Lazy<FrozenDictionary<string, string>> English = new(() => Load("en"));
    private static readonly Lazy<FrozenDictionary<string, string>> Indonesian = new(() => Load("id"));

    private static readonly FrozenDictionary<string, string> RuntimeEnglish =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Settings.Density.Compact"] = "Compact",
            ["Settings.Density.Comfortable"] = "Comfortable",
            ["Settings.Density.Spacious"] = "Spacious",
            ["Settings.WindowSize.FitToScreen"] = "Fit to Screen",
            ["Settings.WindowSize.Custom"] = "Custom",
            ["Settings.WindowSize.Recommended"] = "Recommended — sized to this monitor",
            ["Settings.WindowSize.Desc"] = "Choose a window size. The selected preset is marked below.",
            ["Settings.Organization.Saved"] = "Organization changes saved.",
            ["Settings.Organization.Failed"] = "The organization change could not be saved. Resolve the conflict and try again.",
            ["Settings.MediaPreferences.SaveFailed"] = "Media preferences could not be saved and were restored. Try again. {0}",
            ["Settings.ImportPreferences.SaveFailed"] = "Import preferences could not be saved and were restored. Try again. {0}",
            ["Settings.Library.NoVault"] = "No Vault is open.",
            ["Settings.Updates.NotChecked"] = "Updates have not been checked yet.",
            ["Settings.Updates.Unavailable"] = "The update check could not complete. Try again when the configured feed is available.",
            ["Settings.Updates.Available"] = "Update available: {0}",
            ["Settings.Updates.Version"] = "Version {0}",
            ["Settings.About.Catalog"] = "Catalog schema {0} · Presentation Contract v{1}",
            ["Settings.About.Profiling"] = "Profiling protocol {0} · {1}",
            ["Settings.About.Renderer"] = "Renderer: Uno Platform Skia Desktop (Win32)",
            ["Settings.About.NoticesUnavailable"] = "Third-party notices are unavailable in this deployment.",
            ["Settings.Trash.Media"] = "Media",
            ["Settings.Trash.Profile"] = "Profile",
            ["Trash.Purge.Single.Title"] = "Permanently delete {0}?",
            ["Trash.Purge.Single.Message"] = "Permanently delete {0} and its managed files? This cannot be undone, and it cannot be restored afterward.",
            ["Trash.Purge.Single.Confirm"] = "Delete permanently",
            ["Trash.Purge.Empty.Title"] = "Empty Trash?",
            ["Trash.Purge.Empty.Message"] = "Permanently delete all {0} items in Trash and their managed files? This cannot be undone, and none can be restored afterward.",
            ["Trash.Purge.Empty.Confirm"] = "Empty Trash permanently",
            ["Health.Status.Healthy"] = "Healthy",
            ["Health.Status.Attention"] = "Needs attention",
            ["Health.Metrics"] = "{0} media · {1} catalog · {2} / {3} cache · {4} trash",
            ["Health.Finding.Generic"] = "Library health issue ({0}). Review it before applying a repair.",
            ["Health.RepairConfirmation"] = "Review this repair before continuing. The plan will be revalidated before it changes anything.",
            ["Faces.ConfirmAs"] = "Confirm as {0}",
            ["Faces.NotPerson"] = "Not {0}",
            ["Faces.ProfilingUnavailable.Title"] = "Face detection is not available right now",
            ["Faces.ProfilingUnavailable.Message"] = "The face analysis engine could not start. People suggestions will not appear for imported media. You can still assign people manually from each Profile. This does not affect your media or library.",
            ["Settings.Theme.SaveFailed"] = "The theme preference could not be saved: {0}",
            ["Settings.Density.SaveFailed"] = "The density preference could not be saved: {0}",
            ["Settings.Motion.SaveFailed"] = "The motion preference could not be saved: {0}",
            ["Settings.LoadFailed"] = "Settings could not be loaded.",
            ["Settings.ThirdPartyNotices.LoadFailed"] = "Third-party notices could not be loaded.",

            ["Common.Any"] = "Any",
            ["Common.Any.Lower"] = "any",
            ["Common.Profile"] = "Profile",
            ["Media.Count.One"] = "1 item",
            ["Media.Count.Many"] = "{0} items",
            ["MediaGrid.Type.All"] = "All types",
            ["MediaGrid.Type.Images"] = "Images",
            ["MediaGrid.Type.Videos"] = "Videos",
            ["MediaGrid.Type.Models"] = "Models",
            ["MediaGrid.Relation.All"] = "All relations",
            ["MediaGrid.Relation.Owned"] = "Owned",
            ["MediaGrid.Relation.AppearsIn"] = "Appears In",
            ["MediaGrid.Relation.Manual"] = "Manual",
            ["MediaGrid.Sort.NewestFirst"] = "Newest first",
            ["MediaGrid.Sort.OldestFirst"] = "Oldest first",
            ["MediaGrid.Sort.NameAscending"] = "Name A-Z",
            ["MediaGrid.Sort.CapturedNewestFirst"] = "Captured newest",
            ["MediaGrid.Sort.SizeLargestFirst"] = "Largest first",
            ["MediaGrid.State.Loading"] = "Loading media…",
            ["MediaGrid.State.Empty"] = "This Profile does not have media yet.",
            ["MediaGrid.State.NoResults"] = "No media matches these filters.",
            ["MediaGrid.State.Updating"] = "Media is updating in the background.",
            ["MediaGrid.State.PreviewFailure"] = "A preview could not be shown. Open the media item for details.",
            ["MediaGrid.State.QueryError"] = "Media could not be loaded. Try refreshing the Profile.",
            ["MediaGrid.Range"] = "{0}–{1} of {2}",
            ["Media.Type.Image"] = "Image",
            ["Media.Type.Video"] = "Video",
            ["Media.Type.Model"] = "Model",
            ["Inspector.Who"] = "Who",
            ["Inspector.Where"] = "Where",
            ["Inspector.When"] = "When",
            ["Inspector.How"] = "How",

            ["Gallery.RelatedPicker.Title"] = "Filter by Related Profile",
            ["Gallery.RelatedPicker.Prompt"] = "Select a Profile to filter related Profiles:",
            ["Gallery.Sort.Recent"] = "Recently Updated",
            ["Gallery.Sort.NameAsc"] = "Name A-Z",
            ["Gallery.Sort.NameDesc"] = "Name Z-A",
            ["Gallery.Sort.RatingDesc"] = "Rating High-Low",
            ["Gallery.Sort.RatingAsc"] = "Rating Low-High",
            ["Gallery.Sort.MediaCount"] = "Media Count",
            ["Gallery.Related.Label"] = "Related: {0}",
            ["Gallery.Related.Select"] = "Select Profile...",
            ["Gallery.Count.One"] = "1 Profile",
            ["Gallery.Count.Many"] = "{0} Profiles",
            ["Gallery.Range"] = "{0}-{1} of {2}",
            ["Gallery.Error.PreferencesLoad"] = "Gallery preferences could not be loaded.",
            ["Gallery.Error.FiltersLoad"] = "Filter options could not be loaded.",
            ["Gallery.Error.FiltersRefresh"] = "Filter options could not be refreshed.",
            ["Gallery.Error.Load"] = "Gallery could not be loaded.",
            ["Gallery.Error.PreferencesSave"] = "Gallery preferences could not be saved.",
            ["Gallery.Error.Suggestions"] = "Search suggestions are unavailable right now.",
            ["Gallery.Filter.Search"] = "Search: {0}",
            ["Gallery.Filter.Category"] = "Category: {0}",
            ["Gallery.Filter.Tag"] = "Tag: {0}",
            ["Gallery.Filter.Favorites"] = "Favorites",
            ["Gallery.Filter.Rating"] = "Rating {0}-{1}",
            ["Gallery.Filter.HasImages"] = "Has Images",
            ["Gallery.Filter.HasVideos"] = "Has Videos",
            ["Gallery.Filter.HasModels"] = "Has Models",
            ["Gallery.Filter.SelectedProfile"] = "selected Profile",
            ["Gallery.Filter.RelatedTo"] = "Related to {0}",
            ["Gallery.Filter.SharedMedia"] = "Has Shared Media",
            ["Gallery.Filter.ConfirmedFace"] = "Has Confirmed Face Relation",
            ["Gallery.Filter.ManualRelation"] = "Has Manual Relation",
            ["Gallery.Filter.UnresolvedUnknown"] = "Unresolved (Unknown)",

            ["Home.Error.Load"] = "Home could not be loaded.",
            ["Home.Error.ProfileDirectoryUnavailable"] = "The Profile folder cannot be opened because library operations are unavailable.",
            ["Home.Error.ProfileDirectoryOpen"] = "The Profile folder could not be opened.",
            ["Home.Spotlight.Position"] = "{0} of {1}",
            ["Home.Attention.Verification.Title"] = "Waiting for your choices",
            ["Home.Attention.Verification.Detail"] = "{0} — choose who these {1} media are for.",
            ["Home.Attention.Import.Title"] = "Import needs attention",
            ["Home.Attention.Import.Detail"] = "{0} stopped before finishing. You can try it again from Import.",
            ["Home.Attention.Cleanup.Title"] = "Original files need attention",
            ["Home.Attention.Cleanup.Detail"] = "{0} is in your library, but {1} original file(s) could not be removed from the source folder.",
            ["Home.Attention.Reconciliation.Title"] = "Some files need attention",
            ["Home.Attention.Reconciliation.Detail"] = "{0} item(s) could not be filed into their final place in your library.",
            ["Home.Attention.Faces.Title"] = "People to confirm",
            ["Home.Attention.Faces.Detail"] = "{0} face(s) are waiting for you to say who they are.",
            ["Home.Evidence.Shared.One"] = "1 shared media item",
            ["Home.Evidence.Shared.Many"] = "{0} shared media items",
            ["Home.Evidence.Face.One"] = "1 confirmed face association",
            ["Home.Evidence.Face.Many"] = "{0} confirmed face associations",
            ["Home.Evidence.Manual"] = "a manual relation",
            ["Home.Chronicle.Media.One"] = "1 media added this month",
            ["Home.Chronicle.Media.Many"] = "{0} media added this month",
            ["Home.Chronicle.Connection.One"] = "1 evidence-backed profile connection formed or updated",
            ["Home.Chronicle.Connection.Many"] = "{0} evidence-backed profile connections formed or updated",
            ["Home.Chronicle.Face.One"] = "1 face confirmed this month",
            ["Home.Chronicle.Face.Many"] = "{0} faces confirmed this month",
            ["Home.Chronicle.Profile.One"] = "1 profile created this month",
            ["Home.Chronicle.Profile.Many"] = "{0} profiles created this month",

            ["Faces.Picker.AssignTitle"] = "Assign Other Profile",
            ["Faces.Picker.ReassignTitle"] = "Reassign Face to Profile",
            ["Faces.Picker.AssignPrompt"] = "Choose a Profile to assign this face detection to:",
            ["Faces.Error.MediaNoProfile"] = "This media item has no Profile to open it in.",
            ["Faces.Error.MediaOpen"] = "This media item could not be opened.",
            ["Faces.Status.OperationFailed"] = "The face review action could not be completed.",
            ["Faces.Status.NoTarget"] = "No target Profile is available for confirmation.",
            ["Faces.Status.Confirmed"] = "Face confirmed.",
            ["Faces.Status.ConfirmedSuccessfully"] = "Face confirmed successfully.",
            ["Faces.Status.ConfirmFailed"] = "The face could not be confirmed.",
            ["Faces.Status.Rejected"] = "Face rejected.",
            ["Faces.Status.RejectFailed"] = "The face could not be rejected.",
            ["Faces.Status.Assigned"] = "Face assigned to Profile.",
            ["Faces.Status.AssignFailed"] = "The face could not be assigned.",
            ["Faces.Label.ConfirmedProfile"] = "Confirmed Profile",
            ["Faces.Label.AssignedProfile"] = "Assigned Profile",
            ["Faces.Badge.Confirmed"] = "Confirmed",
            ["Faces.Badge.Suggested"] = "Suggested (Non-authoritative)",
            ["Faces.Badge.Rejected"] = "Rejected",
            ["Faces.Badge.Unresolved"] = "Unresolved",
            ["Faces.YuNetUnavailable"] = "YuNet score unavailable",
            ["Faces.DetectionConfidence"] = "Face detection confidence {0}. It says a face is here, not who it is.",
            ["Faces.DetectionConfidenceMissing"] = "No face-detection confidence was recorded.",
            ["Faces.FrameAt"] = "Frame at {0}",
            ["Faces.Identity.None"] = "No Identity suggestion",
            ["Faces.Identity.One"] = "1 Identity suggestion",
            ["Faces.Identity.Many"] = "{0} Identity suggestions",
            ["Faces.Unassigned"] = "Unassigned",
            ["Faces.UnnamedProfile"] = "Unnamed Profile",

            ["Profile.Error.Open"] = "This Profile could not be opened.",
            ["Profile.Error.Refresh"] = "This Profile could not be refreshed.",
            ["Profile.Error.NotFound"] = "Profile not found.",
            ["Profile.Unknown.SelectMedia"] = "Select active media items below to resolve this UNKNOWN Profile.",
            ["Profile.Rename.Pending"] = "Renaming files... (reconciliation pending)",
            ["Profile.Rename.Empty"] = "Display name cannot be empty.",
            ["Profile.Rename.NameUpdated"] = "Name updated.",
            ["Profile.Rename.NeedsAttention"] = "Folder renaming needs attention.",
            ["Profile.Rename.Success"] = "Profile renamed successfully.",
            ["Profile.Rename.Failed"] = "The Profile could not be renamed.",
            ["Profile.Folder.ServiceUnavailable"] = "Profile operations are unavailable.",
            ["Profile.Folder.Opened"] = "Opened in Windows Explorer.",
            ["Profile.Folder.OpenFailed"] = "The Profile folder could not be opened.",
            ["Profile.Cover.Set"] = "Cover set.",
            ["Profile.Cover.Cleared"] = "Cover cleared.",
            ["Profile.Cover.Failed"] = "The Cover could not be changed.",
            ["Profile.Banner.Set"] = "Banner set.",
            ["Profile.Banner.Cleared"] = "Banner cleared.",
            ["Profile.Banner.Failed"] = "The Banner could not be changed.",
            ["Profile.Cover.ChooseVideoFrame"] = "Choose which frame of this video the Cover should use.",
            ["Profile.Customize.Unavailable"] = "Customization is unavailable without the application shell.",
            ["Profile.Cover.AppearanceSaveFailed"] = "The Cover appearance could not be saved.",
            ["Profile.Rating.SaveFailed"] = "That rating could not be saved.",
            ["Profile.Favorite.SaveFailed"] = "The favorite state could not be saved.",
            ["Profile.Category.None"] = "(None)",
            ["Profile.Metadata.Updated"] = "Profile metadata updated.",
            ["Profile.Metadata.Failed"] = "Profile metadata could not be updated.",
            ["Profile.Face.ReassignFailed"] = "The face detection could not be reassigned.",
            ["Profile.Media.LibraryNotOpen"] = "The media file is not available until the library is open.",
            ["Profile.Media.DefaultOpenFailed"] = "Windows could not open this media item with its default app.",
            ["Profile.Unknown.NoSelection"] = "No media items selected for assignment.",
            ["Profile.Unknown.Assigned"] = "Assigned {0} items to Profile.",
            ["Profile.Unknown.AssignedResolved"] = "Assigned {0} items. UNKNOWN Profile is now fully resolved and leaves the active queue.",
            ["Profile.Unknown.AssignedRemaining"] = "Assigned {0} items. UNKNOWN Profile has {1} active items remaining.",
            ["Profile.Unknown.AssignFailed"] = "The media could not be assigned.",
            ["Profile.Unknown.NewNameRequired"] = "New Profile name is required.",
            ["Profile.Unknown.Created"] = "Created Profile '{0}' with {1} items.",
            ["Profile.Unknown.CreatedResolved"] = "Created Profile '{0}'. UNKNOWN Profile is now fully resolved and leaves the active queue.",
            ["Profile.Unknown.CreatedRemaining"] = "Created Profile '{0}'. UNKNOWN has {1} active items remaining.",
            ["Profile.Unknown.CreateFailed"] = "A Profile could not be created from UNKNOWN media.",
            ["Assignment.Cluster.Title"] = "Grouped assignment review",
            ["Assignment.Cluster.Description"] = "Each row contains media with the same import evidence. Suggestions are hints, never certainty.",
            ["Assignment.Cluster.UnknownSource"] = "same import context",
            ["Assignment.Cluster.Candidate"] = "{0} items from {1}; suggested Profile: {2}",
            ["Assignment.Cluster.Unresolved"] = "{0} items from {1} need one assignment decision",
            ["Assignment.Cluster.UseCandidate"] = "Assign all to {0}",
            ["Assignment.Cluster.ChooseOther"] = "Choose another Profile…",
            ["Assignment.Cluster.KeepUnknown"] = "Keep unassigned",
            ["Assignment.Cluster.Accepted"] = "Assigned {0} grouped media items.",
            ["Assignment.Cluster.KeptUnknown"] = "Media remains safely unassigned.",
            ["Assignment.Cluster.Failed"] = "The grouped assignment could not be applied.",
            ["Assignment.Cluster.PickerFailed"] = "Profiles could not be loaded.",
            ["Assignment.Cluster.ChooseTitle"] = "Assign grouped media",
            ["Assignment.Cluster.ChoosePrompt"] = "Choose the Profile for this evidence group:",
            ["Profile.Relation.Owner"] = "Owner",
            ["Profile.Relation.Appears"] = "Appears In",
            ["Profile.Relation.Manual"] = "Manual",
        }.ToFrozenDictionary(StringComparer.Ordinal);

    private static readonly FrozenDictionary<string, string> RuntimeIndonesian =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Settings.MediaPreferences.SaveFailed"] = "Preferensi media tidak dapat disimpan dan telah dikembalikan. Coba lagi. {0}",
            ["Settings.ImportPreferences.SaveFailed"] = "Preferensi impor tidak dapat disimpan dan telah dikembalikan. Coba lagi. {0}",
            ["Settings.Density.Compact"] = "Rapat",
            ["Settings.Density.Comfortable"] = "Nyaman",
            ["Settings.Density.Spacious"] = "Lega",
            ["Settings.WindowSize.FitToScreen"] = "Sesuaikan ke Layar",
            ["Settings.WindowSize.Custom"] = "Kustom",
            ["Settings.WindowSize.Recommended"] = "Disarankan — disesuaikan dengan monitor ini",
            ["Settings.WindowSize.Desc"] = "Pilih ukuran jendela. Preset yang sedang digunakan ditandai di bawah.",
            ["Settings.Organization.Saved"] = "Perubahan organisasi telah disimpan.",
            ["Settings.Organization.Failed"] = "Perubahan organisasi tidak dapat disimpan. Selesaikan konflik lalu coba lagi.",
            ["Settings.Library.NoVault"] = "Tidak ada Vault yang sedang dibuka.",
            ["Settings.Updates.NotChecked"] = "Pembaruan belum diperiksa.",
            ["Settings.Updates.Unavailable"] = "Pemeriksaan pembaruan tidak dapat diselesaikan. Coba lagi saat feed yang dikonfigurasi tersedia.",
            ["Settings.Updates.Available"] = "Pembaruan tersedia: {0}",
            ["Settings.Updates.Version"] = "Versi {0}",
            ["Settings.About.Catalog"] = "Skema katalog {0} · Presentation Contract v{1}",
            ["Settings.About.Profiling"] = "Protokol profiling {0} · {1}",
            ["Settings.About.Renderer"] = "Renderer: Uno Platform Skia Desktop (Win32)",
            ["Settings.About.NoticesUnavailable"] = "Pemberitahuan pihak ketiga tidak tersedia pada deployment ini.",
            ["Settings.Trash.Media"] = "Media",
            ["Settings.Trash.Profile"] = "Profil",
            ["Trash.Purge.Single.Title"] = "Hapus {0} secara permanen?",
            ["Trash.Purge.Single.Message"] = "Hapus {0} dan file terkelolanya secara permanen? Tindakan ini tidak dapat dibatalkan dan item tidak dapat dipulihkan setelahnya.",
            ["Trash.Purge.Single.Confirm"] = "Hapus permanen",
            ["Trash.Purge.Empty.Title"] = "Kosongkan Sampah?",
            ["Trash.Purge.Empty.Message"] = "Hapus permanen seluruh {0} item di Sampah beserta file terkelolanya? Tindakan ini tidak dapat dibatalkan dan tidak ada item yang dapat dipulihkan setelahnya.",
            ["Trash.Purge.Empty.Confirm"] = "Kosongkan Sampah permanen",
            ["Health.Status.Healthy"] = "Sehat",
            ["Health.Status.Attention"] = "Perlu perhatian",
            ["Health.Metrics"] = "{0} media · {1} katalog · {2} / {3} cache · {4} trash",
            ["Health.Finding.Generic"] = "Masalah kesehatan library ({0}). Tinjau sebelum menjalankan perbaikan.",
            ["Health.RepairConfirmation"] = "Tinjau perbaikan ini sebelum melanjutkan. Rencana akan divalidasi ulang sebelum mengubah apa pun.",
            ["Faces.ConfirmAs"] = "Konfirmasi sebagai {0}",
            ["Faces.NotPerson"] = "Bukan {0}",
            ["Faces.ProfilingUnavailable.Title"] = "Deteksi wajah tidak tersedia saat ini",
            ["Faces.ProfilingUnavailable.Message"] = "Mesin analisis wajah tidak dapat dimulai. Saran orang tidak akan muncul untuk media yang diimpor. Anda masih dapat menetapkan orang secara manual dari setiap Profil. Ini tidak mempengaruhi media atau library Anda.",
            ["Settings.Theme.SaveFailed"] = "Preferensi tema tidak dapat disimpan: {0}",
            ["Settings.Density.SaveFailed"] = "Preferensi kepadatan tidak dapat disimpan: {0}",
            ["Settings.Motion.SaveFailed"] = "Preferensi gerakan tidak dapat disimpan: {0}",
            ["Settings.LoadFailed"] = "Pengaturan tidak dapat dimuat.",
            ["Settings.ThirdPartyNotices.LoadFailed"] = "Pemberitahuan pihak ketiga tidak dapat dimuat.",

            ["Common.Any"] = "Apa pun",
            ["Common.Any.Lower"] = "apa pun",
            ["Common.Profile"] = "Profil",
            ["Media.Count.One"] = "1 item",
            ["Media.Count.Many"] = "{0} item",
            ["MediaGrid.Type.All"] = "Semua jenis",
            ["MediaGrid.Type.Images"] = "Gambar",
            ["MediaGrid.Type.Videos"] = "Video",
            ["MediaGrid.Type.Models"] = "Model",
            ["MediaGrid.Relation.All"] = "Semua relasi",
            ["MediaGrid.Relation.Owned"] = "Dimiliki",
            ["MediaGrid.Relation.AppearsIn"] = "Muncul di",
            ["MediaGrid.Relation.Manual"] = "Manual",
            ["MediaGrid.Sort.NewestFirst"] = "Terbaru dulu",
            ["MediaGrid.Sort.OldestFirst"] = "Terlama dulu",
            ["MediaGrid.Sort.NameAscending"] = "Nama A-Z",
            ["MediaGrid.Sort.CapturedNewestFirst"] = "Pengambilan terbaru",
            ["MediaGrid.Sort.SizeLargestFirst"] = "Terbesar dulu",
            ["MediaGrid.State.Loading"] = "Memuat media…",
            ["MediaGrid.State.Empty"] = "Profil ini belum memiliki media.",
            ["MediaGrid.State.NoResults"] = "Tidak ada media yang cocok dengan filter ini.",
            ["MediaGrid.State.Updating"] = "Media sedang diperbarui di latar belakang.",
            ["MediaGrid.State.PreviewFailure"] = "Pratinjau tidak dapat ditampilkan. Buka item media untuk detail.",
            ["MediaGrid.State.QueryError"] = "Media tidak dapat dimuat. Coba perbarui Profil.",
            ["MediaGrid.Range"] = "{0}–{1} dari {2}",
            ["Media.Type.Image"] = "Gambar",
            ["Media.Type.Video"] = "Video",
            ["Media.Type.Model"] = "Model",
            ["Inspector.Who"] = "Siapa",
            ["Inspector.Where"] = "Di mana",
            ["Inspector.When"] = "Kapan",
            ["Inspector.How"] = "Bagaimana",

            ["Gallery.RelatedPicker.Title"] = "Filter berdasarkan Profil Terkait",
            ["Gallery.RelatedPicker.Prompt"] = "Pilih Profil untuk memfilter Profil terkait:",
            ["Gallery.Sort.Recent"] = "Baru Diperbarui",
            ["Gallery.Sort.NameAsc"] = "Nama A-Z",
            ["Gallery.Sort.NameDesc"] = "Nama Z-A",
            ["Gallery.Sort.RatingDesc"] = "Rating Tinggi-Rendah",
            ["Gallery.Sort.RatingAsc"] = "Rating Rendah-Tinggi",
            ["Gallery.Sort.MediaCount"] = "Jumlah Media",
            ["Gallery.Related.Label"] = "Terkait: {0}",
            ["Gallery.Related.Select"] = "Pilih Profil...",
            ["Gallery.Count.One"] = "1 Profil",
            ["Gallery.Count.Many"] = "{0} Profil",
            ["Gallery.Range"] = "{0}-{1} dari {2}",
            ["Gallery.Error.PreferencesLoad"] = "Preferensi Galeri tidak dapat dimuat.",
            ["Gallery.Error.FiltersLoad"] = "Opsi filter tidak dapat dimuat.",
            ["Gallery.Error.FiltersRefresh"] = "Opsi filter tidak dapat diperbarui.",
            ["Gallery.Error.Load"] = "Galeri tidak dapat dimuat.",
            ["Gallery.Error.PreferencesSave"] = "Preferensi Galeri tidak dapat disimpan.",
            ["Gallery.Error.Suggestions"] = "Saran pencarian sedang tidak tersedia.",
            ["Gallery.Filter.Search"] = "Pencarian: {0}",
            ["Gallery.Filter.Category"] = "Kategori: {0}",
            ["Gallery.Filter.Tag"] = "Tag: {0}",
            ["Gallery.Filter.Favorites"] = "Favorit",
            ["Gallery.Filter.Rating"] = "Rating {0}-{1}",
            ["Gallery.Filter.HasImages"] = "Memiliki Gambar",
            ["Gallery.Filter.HasVideos"] = "Memiliki Video",
            ["Gallery.Filter.HasModels"] = "Memiliki Model",
            ["Gallery.Filter.SelectedProfile"] = "Profil terpilih",
            ["Gallery.Filter.RelatedTo"] = "Terkait dengan {0}",
            ["Gallery.Filter.SharedMedia"] = "Memiliki Media Bersama",
            ["Gallery.Filter.ConfirmedFace"] = "Memiliki Relasi Wajah Terkonfirmasi",
            ["Gallery.Filter.ManualRelation"] = "Memiliki Relasi Manual",
            ["Gallery.Filter.UnresolvedUnknown"] = "Belum Terselesaikan (Unknown)",

            ["Home.Error.Load"] = "Beranda tidak dapat dimuat.",
            ["Home.Error.ProfileDirectoryUnavailable"] = "Folder Profil tidak dapat dibuka karena operasi library tidak tersedia.",
            ["Home.Error.ProfileDirectoryOpen"] = "Folder Profil tidak dapat dibuka.",
            ["Home.Spotlight.Position"] = "{0} dari {1}",
            ["Home.Attention.Verification.Title"] = "Menunggu pilihan Anda",
            ["Home.Attention.Verification.Detail"] = "{0} — pilih Profil tujuan untuk {1} media ini.",
            ["Home.Attention.Import.Title"] = "Impor perlu perhatian",
            ["Home.Attention.Import.Detail"] = "{0} berhenti sebelum selesai. Anda dapat mencobanya lagi dari Impor.",
            ["Home.Attention.Cleanup.Title"] = "File asli perlu perhatian",
            ["Home.Attention.Cleanup.Detail"] = "{0} sudah ada di library, tetapi {1} file asli tidak dapat dihapus dari folder sumber.",
            ["Home.Attention.Reconciliation.Title"] = "Beberapa file perlu perhatian",
            ["Home.Attention.Reconciliation.Detail"] = "{0} item tidak dapat ditempatkan ke lokasi akhirnya di library.",
            ["Home.Attention.Faces.Title"] = "Orang yang perlu dikonfirmasi",
            ["Home.Attention.Faces.Detail"] = "{0} wajah menunggu konfirmasi identitas Anda.",
            ["Home.Evidence.Shared.One"] = "1 item media bersama",
            ["Home.Evidence.Shared.Many"] = "{0} item media bersama",
            ["Home.Evidence.Face.One"] = "1 asosiasi wajah terkonfirmasi",
            ["Home.Evidence.Face.Many"] = "{0} asosiasi wajah terkonfirmasi",
            ["Home.Evidence.Manual"] = "relasi manual",
            ["Home.Chronicle.Media.One"] = "1 media ditambahkan bulan ini",
            ["Home.Chronicle.Media.Many"] = "{0} media ditambahkan bulan ini",
            ["Home.Chronicle.Connection.One"] = "1 koneksi Profil berbasis bukti dibuat atau diperbarui",
            ["Home.Chronicle.Connection.Many"] = "{0} koneksi Profil berbasis bukti dibuat atau diperbarui",
            ["Home.Chronicle.Face.One"] = "1 wajah dikonfirmasi bulan ini",
            ["Home.Chronicle.Face.Many"] = "{0} wajah dikonfirmasi bulan ini",
            ["Home.Chronicle.Profile.One"] = "1 Profil dibuat bulan ini",
            ["Home.Chronicle.Profile.Many"] = "{0} Profil dibuat bulan ini",

            ["Faces.Picker.AssignTitle"] = "Tetapkan Profil Lain",
            ["Faces.Picker.ReassignTitle"] = "Tetapkan Ulang Wajah ke Profil",
            ["Faces.Picker.AssignPrompt"] = "Pilih Profil untuk menetapkan deteksi wajah ini:",
            ["Faces.Error.MediaNoProfile"] = "Item media ini tidak memiliki Profil untuk dibuka.",
            ["Faces.Error.MediaOpen"] = "Item media ini tidak dapat dibuka.",
            ["Faces.Status.OperationFailed"] = "Tindakan tinjauan wajah tidak dapat diselesaikan.",
            ["Faces.Status.NoTarget"] = "Tidak ada Profil tujuan yang tersedia untuk konfirmasi.",
            ["Faces.Status.Confirmed"] = "Wajah dikonfirmasi.",
            ["Faces.Status.ConfirmedSuccessfully"] = "Wajah berhasil dikonfirmasi.",
            ["Faces.Status.ConfirmFailed"] = "Wajah tidak dapat dikonfirmasi.",
            ["Faces.Status.Rejected"] = "Wajah ditolak.",
            ["Faces.Status.RejectFailed"] = "Wajah tidak dapat ditolak.",
            ["Faces.Status.Assigned"] = "Wajah ditetapkan ke Profil.",
            ["Faces.Status.AssignFailed"] = "Wajah tidak dapat ditetapkan.",
            ["Faces.Label.ConfirmedProfile"] = "Profil Terkonfirmasi",
            ["Faces.Label.AssignedProfile"] = "Profil yang Ditetapkan",
            ["Faces.Badge.Confirmed"] = "Terkonfirmasi",
            ["Faces.Badge.Suggested"] = "Saran (Non-otoritatif)",
            ["Faces.Badge.Rejected"] = "Ditolak",
            ["Faces.Badge.Unresolved"] = "Belum Terselesaikan",
            ["Faces.YuNetUnavailable"] = "Skor YuNet tidak tersedia",
            ["Faces.DetectionConfidence"] = "Keyakinan deteksi wajah {0}. Nilai ini menunjukkan ada wajah, bukan siapa orangnya.",
            ["Faces.DetectionConfidenceMissing"] = "Tidak ada skor keyakinan deteksi wajah yang tersimpan.",
            ["Faces.FrameAt"] = "Frame pada {0}",
            ["Faces.Identity.None"] = "Tidak ada saran identitas",
            ["Faces.Identity.One"] = "1 saran identitas",
            ["Faces.Identity.Many"] = "{0} saran identitas",
            ["Faces.Unassigned"] = "Belum ditetapkan",
            ["Faces.UnnamedProfile"] = "Profil Tanpa Nama",

            ["Profile.Error.Open"] = "Profil ini tidak dapat dibuka.",
            ["Profile.Error.Refresh"] = "Profil ini tidak dapat diperbarui.",
            ["Profile.Error.NotFound"] = "Profil tidak ditemukan.",
            ["Profile.Unknown.SelectMedia"] = "Pilih item media aktif di bawah untuk menyelesaikan Profil UNKNOWN ini.",
            ["Profile.Rename.Pending"] = "Mengganti nama file... (rekonsiliasi tertunda)",
            ["Profile.Rename.Empty"] = "Nama tampilan tidak boleh kosong.",
            ["Profile.Rename.NameUpdated"] = "Nama diperbarui.",
            ["Profile.Rename.NeedsAttention"] = "Penggantian nama folder perlu perhatian.",
            ["Profile.Rename.Success"] = "Profil berhasil diganti namanya.",
            ["Profile.Rename.Failed"] = "Profil tidak dapat diganti namanya.",
            ["Profile.Folder.ServiceUnavailable"] = "Operasi Profil tidak tersedia.",
            ["Profile.Folder.Opened"] = "Dibuka di Windows Explorer.",
            ["Profile.Folder.OpenFailed"] = "Folder Profil tidak dapat dibuka.",
            ["Profile.Cover.Set"] = "Cover ditetapkan.",
            ["Profile.Cover.Cleared"] = "Cover dikosongkan.",
            ["Profile.Cover.Failed"] = "Cover tidak dapat diubah.",
            ["Profile.Banner.Set"] = "Banner ditetapkan.",
            ["Profile.Banner.Cleared"] = "Banner dikosongkan.",
            ["Profile.Banner.Failed"] = "Banner tidak dapat diubah.",
            ["Profile.Cover.ChooseVideoFrame"] = "Pilih frame video yang akan digunakan sebagai Cover.",
            ["Profile.Customize.Unavailable"] = "Kustomisasi tidak tersedia tanpa shell aplikasi.",
            ["Profile.Cover.AppearanceSaveFailed"] = "Tampilan Cover tidak dapat disimpan.",
            ["Profile.Rating.SaveFailed"] = "Rating tersebut tidak dapat disimpan.",
            ["Profile.Favorite.SaveFailed"] = "Status favorit tidak dapat disimpan.",
            ["Profile.Category.None"] = "(Tidak ada)",
            ["Profile.Metadata.Updated"] = "Metadata Profil diperbarui.",
            ["Profile.Metadata.Failed"] = "Metadata Profil tidak dapat diperbarui.",
            ["Profile.Face.ReassignFailed"] = "Deteksi wajah tidak dapat ditetapkan ulang.",
            ["Profile.Media.LibraryNotOpen"] = "File media tidak tersedia sampai library dibuka.",
            ["Profile.Media.DefaultOpenFailed"] = "Windows tidak dapat membuka item media ini dengan aplikasi defaultnya.",
            ["Profile.Unknown.NoSelection"] = "Tidak ada item media yang dipilih untuk ditetapkan.",
            ["Profile.Unknown.Assigned"] = "{0} item ditetapkan ke Profil.",
            ["Profile.Unknown.AssignedResolved"] = "{0} item ditetapkan. Profil UNKNOWN kini sepenuhnya terselesaikan dan keluar dari antrean aktif.",
            ["Profile.Unknown.AssignedRemaining"] = "{0} item ditetapkan. Profil UNKNOWN masih memiliki {1} item aktif.",
            ["Profile.Unknown.AssignFailed"] = "Media tidak dapat ditetapkan.",
            ["Profile.Unknown.NewNameRequired"] = "Nama Profil baru wajib diisi.",
            ["Profile.Unknown.Created"] = "Profil '{0}' dibuat dengan {1} item.",
            ["Profile.Unknown.CreatedResolved"] = "Profil '{0}' dibuat. Profil UNKNOWN kini sepenuhnya terselesaikan dan keluar dari antrean aktif.",
            ["Profile.Unknown.CreatedRemaining"] = "Profil '{0}' dibuat. UNKNOWN masih memiliki {1} item aktif.",
            ["Profile.Unknown.CreateFailed"] = "Profil tidak dapat dibuat dari media UNKNOWN.",
            ["Assignment.Cluster.Title"] = "Tinjau penetapan berkelompok",
            ["Assignment.Cluster.Description"] = "Setiap baris berisi media dengan bukti impor yang sama. Saran hanyalah petunjuk, bukan kepastian.",
            ["Assignment.Cluster.UnknownSource"] = "konteks impor yang sama",
            ["Assignment.Cluster.Candidate"] = "{0} item dari {1}; Profil yang disarankan: {2}",
            ["Assignment.Cluster.Unresolved"] = "{0} item dari {1} memerlukan satu keputusan penetapan",
            ["Assignment.Cluster.UseCandidate"] = "Tetapkan semua ke {0}",
            ["Assignment.Cluster.ChooseOther"] = "Pilih Profil lain…",
            ["Assignment.Cluster.KeepUnknown"] = "Biarkan belum ditetapkan",
            ["Assignment.Cluster.Accepted"] = "{0} item media berkelompok telah ditetapkan.",
            ["Assignment.Cluster.KeptUnknown"] = "Media tetap aman dan belum ditetapkan.",
            ["Assignment.Cluster.Failed"] = "Penetapan berkelompok tidak dapat diterapkan.",
            ["Assignment.Cluster.PickerFailed"] = "Daftar Profil tidak dapat dimuat.",
            ["Assignment.Cluster.ChooseTitle"] = "Tetapkan media berkelompok",
            ["Assignment.Cluster.ChoosePrompt"] = "Pilih Profil untuk kelompok bukti ini:",
            ["Profile.Relation.Owner"] = "Pemilik",
            ["Profile.Relation.Appears"] = "Muncul di",
            ["Profile.Relation.Manual"] = "Manual",
        }.ToFrozenDictionary(StringComparer.Ordinal);

    public static bool TryGet(string languageCode, string key, out string value)
    {
        var table = string.Equals(languageCode, "id", StringComparison.OrdinalIgnoreCase) ? Indonesian.Value : English.Value;
        if (table.TryGetValue(key, out var found) && !string.IsNullOrEmpty(found))
        {
            value = found;
            return true;
        }

        value = string.Empty;
        return false;
    }

    public static IReadOnlyDictionary<string, string> Table(string languageCode) =>
        string.Equals(languageCode, "id", StringComparison.OrdinalIgnoreCase) ? Indonesian.Value : English.Value;

    private static FrozenDictionary<string, string> Load(string language)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        var supplement = string.Equals(language, "id", StringComparison.OrdinalIgnoreCase)
            ? RuntimeIndonesian
            : RuntimeEnglish;
        foreach (var pair in supplement)
        {
            result[pair.Key] = pair.Value;
        }

        try
        {
            using var stream = typeof(LocalizationTables).Assembly
                .GetManifestResourceStream($"Neuterradise.App.Localization.Strings.{language}.xml");
            if (stream is null)
            {
                return result.ToFrozenDictionary(StringComparer.Ordinal);
            }

            var document = XDocument.Load(stream);
            XNamespace x = "http://schemas.microsoft.com/winfx/2006/xaml";
            foreach (var element in document.Root?.Elements() ?? [])
            {
                var key = (string?)element.Attribute(x + "Key");
                if (!string.IsNullOrEmpty(key))
                {
                    result[key] = element.Value;
                }
            }
        }
        catch (Exception exception) when (exception is System.Xml.XmlException or IOException)
        {
            System.Diagnostics.Trace.TraceWarning("Localization table {0} could not be read: {1}", language, exception.GetType().Name);
        }

        return result.ToFrozenDictionary(StringComparer.Ordinal);
    }
}
